sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - 8
  - 6
  - 4
before_install:
  - npm i -g npm@^5.3.0
  - npm -v
  - npm i -g codeclimate-test-reporter
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - npm run semantic-release
addons:
  code_climate:
    repo_token: c2f5565ff4d312c27c2864e45d361d9767f9f6cba820bd705b422ca75f69c706
