sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - 0.10
  - 0.12
  - iojs
  - 4
before_install:
  - npm -v
  - npm i -g codeclimate-test-reporter
before_script:
  - npm prune
  - 'curl -Lo travis_after_all.py https://git.io/vLSON'
script:
  - npm run test
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - npm run semantic-release
addons:
  code_climate:
    repo_token: c2f5565ff4d312c27c2864e45d361d9767f9f6cba820bd705b422ca75f69c706
